# **PyTorch Fundamentals**

In [1]:
import torch # preinstalled in colab
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.11.0+cu128


In [2]:
!nvidia-smi # used to check the usage and other stats of the GPU in colab

Wed Jul 22 07:46:40 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   56C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()`

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# a scalar has no dimensions, it's just a single number
scalar.ndim

0

In [5]:
# Get tensor back as python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# Dimensions of a vector
vector.ndim

1

In [8]:
# Number of elements of a vector
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# Dimensions of MATRIX
MATRIX.ndim

2

In [11]:
# Shape of MATRIX (number of elements)
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
# Dimensions
TENSOR.ndim

3

In [14]:
# Shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# Create a random tensor of size/shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0325, 0.0710, 0.7485, 0.6183],
        [0.1706, 0.3691, 0.7219, 0.3308],
        [0.5484, 0.2652, 0.2560, 0.6363]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224,3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
# challenge - create a random tensor of the size and dimension of your choice
# print the tensor, print is shape and dimensions

rand_tensor = torch.rand(size = (3,3,3,3))
print(rand_tensor)
print(rand_tensor.shape)
print(rand_tensor.ndim)

tensor([[[[0.3169, 0.4699, 0.9416],
          [0.4297, 0.2438, 0.5878],
          [0.1627, 0.9564, 0.6667]],

         [[0.3152, 0.2818, 0.7793],
          [0.9954, 0.1859, 0.3496],
          [0.0955, 0.8787, 0.9533]],

         [[0.0675, 0.9761, 0.7278],
          [0.6613, 0.5026, 0.0854],
          [0.4702, 0.1509, 0.0605]]],


        [[[0.4882, 0.8140, 0.4683],
          [0.0984, 0.2430, 0.5875],
          [0.0866, 0.2883, 0.1703]],

         [[0.1787, 0.9083, 0.9500],
          [0.2364, 0.5300, 0.0881],
          [0.7071, 0.0423, 0.7374]],

         [[0.7027, 0.2829, 0.8736],
          [0.7312, 0.6524, 0.4287],
          [0.7140, 0.6028, 0.5871]]],


        [[[0.2897, 0.6993, 0.9674],
          [0.9911, 0.6838, 0.3351],
          [0.3376, 0.3689, 0.5186]],

         [[0.9542, 0.5514, 0.7081],
          [0.1417, 0.0086, 0.9069],
          [0.8503, 0.7995, 0.9478]],

         [[0.1100, 0.1041, 0.3362],
          [0.6731, 0.2132, 0.8004],
          [0.5077, 0.8256, 0.5203]]]])
torch

### Zeros and ones

In [20]:
# Create a tesnor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
# check the dtype of a tensor
ones.dtype, random_tensor.dtype

(torch.float32, torch.float32)

### float32 is the default dtype of a tensor

In [24]:
# challenge - create each a tensor with zeros and ones with size and dimensions of your own choice.
# print the tensor, print is shape and dimensions

ones_ = torch.ones(5,5,5)
zeros_ = torch.zeros((2,2,2))

print(ones_, zeros_)
print(ones_.shape, zeros_.shape)
print(ones_.ndim, ones_.ndim)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]) tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
torch.Size([5, 5, 5]) torch.Size([2, 2, 2])
3 3


### Creating a range of tensors and tensors-like.

In [25]:
# Use torch.range() and get deprecated message, instead use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# Create tensors like (create a tensor with the same shape as another tensor)
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
one_to_ten.shape, ten_zeros.shape

(torch.Size([10]), torch.Size([10]))

In [28]:
one_to_ten.ndim, ten_zeros.ndim

(1, 1)

In [29]:
# challenge - create a tensor and replicate its shape in another tensor of ones

rand_tensor # this will be used for replication

ones_rand_tensor = torch.ones_like(rand_tensor)
print(ones_rand_tensor)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])


### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch
and deep learning:
  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not on the right device

In [30]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None)
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
# Float 16 tensor
float_16 = torch.tensor([3, 6, 9],
                        dtype = torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
float_32_tensor == float_16

tensor([True, True, True])

In [34]:
# important parameters of torch.tensor()

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor (e.g. float32 or float 16)
                               device = None, # what device is your tensor on. default = 'cpu'
                               requires_grad = False) # whether or not to track gradients with this tensors operations

In [35]:
# type casting of tensors in pytorch
float_16_tensor = float_32_tensor.type(torch.half) # or it can be float_32_tensor.type(torch.float 16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### some common dtypes of tensors
1. float32 -> `torch.float32` or `torch.float`
2. float64 -> `torch.float64` or `torch.double`
3. float16 -> `torch.float16` or `torch.half`

### Tensor attributes

In [36]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [37]:
# lets try to multiply an int32 tensor with a float32 tensor
int_32_tensor = torch.tensor([3, 6, 9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [38]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [39]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

some_tensor.size(), some_tensor.shape # .size() is a function and .shape is an attribute
# both show the number of elements

(torch.Size([3, 4]), torch.Size([3, 4]))

In [40]:
# Find out details about some_tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}') # default is CPU

tensor([[0.7729, 0.4374, 0.7573, 0.4563],
        [0.1329, 0.7044, 0.1687, 0.5729],
        [0.4156, 0.7752, 0.3919, 0.1216]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors

Tensor operations inlcude:
* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matrix multiplication

In [41]:
# Addition
# Create  a tensor
tensor = torch.Tensor([1,2,3])
tensor + 10, tensor + 100 # similar to scaler addition to vectors

(tensor([11., 12., 13.]), tensor([101., 102., 103.]))

In [42]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([10., 20., 30.])

In [43]:
# Subtract 10
tensor - 10

tensor([ 0., 10., 20.])

In [44]:
# Tryout PyTorch in-built functions

tensor_2 = torch.Tensor([2, 3, 4])

torch.mul(tensor_2, 10), torch.add(10, torch.Tensor([5, 6, 7]))

(tensor([20., 30., 40.]), tensor([15., 16., 17.]))

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning.
1. Element-wise multiplication
2. Matrix to matrix multiplication

There are two rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
  * `(2, 3) @ (3, 2)` -> `(2, 2)`
  * `(3, 2) @ (2, 3)` -> `(3, 3)`

In [45]:
# example - this won't work
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

In [46]:
# Element-wise multiplication
tensor = torch.Tensor([1, 2, 3])

print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1., 2., 3.]) * tensor([1., 2., 3.])
Equals: tensor([1., 4., 9.])


In [47]:
# Matrix multiplication

%%time
torch.matmul(tensor, tensor) # can also use torch.mm()

CPU times: user 1.31 ms, sys: 48 µs, total: 1.36 ms
Wall time: 17.3 ms


tensor(14.)

In [48]:
# Similar to torch.matmul()

%%time
tensor @ tensor

CPU times: user 53 µs, sys: 0 ns, total: 53 µs
Wall time: 57.5 µs


tensor(14.)

In [49]:
# Matrix multiplication by hand

%%time
value  = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14.)
CPU times: user 1.66 ms, sys: 107 µs, total: 1.77 ms
Wall time: 5.12 ms


* Traditional python for loop is almost 10x slower than Pytorch's vectorized functions

### One of the most common errors in deep learning is shape errors.

In [50]:
# Shapes for matrix multiplication
tensor_A = torch.Tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
tensor_A.shape, tensor_B.shape # won't work as the inner dimensions must match

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors

A **transpose** switches the axes or dimensions of a given tensor.

In [51]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [52]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [53]:
# The matrix multiplication operation works when tensor_B is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A: {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} -> inner dimensions must match')
print(f'Output:\n')
output = torch.matmul(tensor_A, tensor_B.T.to(tensor_A.dtype)) # without using .to(tensor_A.dtype) we will get a traceback in the latest version of pytorch
print(output)
print(f'\nOutput shape: {output.shape}')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A: torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) -> inner dimensions must match
Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [54]:
# continue from 23

## Finding the min-max, mean, sum, etc (tensor aggregation)

In [55]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [57]:
# Fina the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [58]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatypes to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [59]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [60]:
# positional min and max
x.argmin(), x.argmax() # tells the index of the min and max values

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors.
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [61]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape, x.size(), x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 torch.Size([9]),
 torch.float32)

In [62]:
# Add an extra dimension # total elements should equal to the original tensor
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [63]:
# or it can be a column tensor
x_col = x.reshape(9,1)
x_col, x_col.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [64]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# Changing z changes x (because a view of a tensor shares the memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [66]:
import numpy as np # we can also use numpy to check if memory is being shared bw the 2 tensors
np.shares_memory(z, x)

True

In [67]:
# Stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0) # stacked vertically
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [68]:
x_stacked = torch.stack([x, x, x, x], dim = 1) # stacked horizontally
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [69]:
# torch.squeeze - removes all single dimensions from a target tensor
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]),
 2)

In [70]:
# squeeze
x_reshaped.squeeze()

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [71]:
# torch.unsqueeze() - adds a single dimension to a target dimension at a specific dimension
x_reshaped.unsqueeze(dim = 0)

tensor([[[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [72]:
# torch.permute - rearranges the dimensions of a target tensor in a specific order
x_original = torch.rand(size = (224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->, 1->2, 2->0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [73]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [74]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape, x.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [75]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [76]:
# Let's index on the middle bracket (dim = 1)
x[0, 0], x[0][0] # both indexing styles are same

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [77]:
# Let's index on the most inner bracket (last dimension)
x[0, 0, 0], x[0][0][0] # both indexing styles are same

(tensor(1), tensor(1))

In [78]:
x[0, 1, 1]

tensor(5)

In [79]:
# challenge - show the number 9 from the tensor
x[0,2,2]

tensor(9)

In [80]:
# You can also use ':' to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [81]:
# Get all values of 0th and last dimensions but only index 1 of 2nd dimension
x[:, 1, 1]

tensor([5])

In [82]:
x[:, 0, 0]

tensor([1])

In [83]:
# Get index 0 of 0th and last dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [84]:
# challenge - index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

NumPy is a popular scientific python numerical computing library and because of this , PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [85]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
# tensor = torch.from_numpy(array).type(torch.float32) to get the tensor in pytorch's default dtype
array, tensor # default dtype will be float64 as it is numpy's default dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [86]:
# change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor # it doesn't alter the tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [87]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor # changes the array's dtype to float32 when converted into a tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [88]:
# Change the tensor, what happens to 'numpy_tensor'
tensor = tensor + 1
tensor, numpy_tensor # don't share memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a `random seed`.

Essentially what the random seed does is 'flavour' the randomness

In [89]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9364, 0.8423, 0.3749, 0.2814],
        [0.2478, 0.8831, 0.6163, 0.6349],
        [0.8376, 0.4624, 0.8767, 0.6183]])
tensor([[0.1809, 0.7415, 0.4809, 0.6143],
        [0.4951, 0.9637, 0.1331, 0.2571],
        [0.2938, 0.1594, 0.0546, 0.9530]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [90]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42 # can be anything

torch.manual_seed(RANDOM_SEED) # works only for a single block of code
random_tensor_C  = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D  = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensor and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything smooth and good.

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation

In [91]:
!nvidia-smi

Wed Jul 22 07:46:41 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P0             30W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [92]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [93]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [94]:
# Count the number of devices
torch.cuda.device_count()

1

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:
  > E.g. run on GPU if available, else default to CPU.

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [95]:
# Create a tensor (default on the CPU)

tensor = torch.Tensor([1, 2, 3]) # by default

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1., 2., 3.]) cpu


In [96]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1., 2., 3.], device='cuda:0')

### 4. Moving tensors back to the CPU

In [97]:
# If tensor is on GPU, can't transform it ti NumPy
import numpy as np
# tensor_on_gpu.numpy() -> won't work

In [98]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu, tensor_on_gpu # tensor_on_gpu remains unchanged

(array([1., 2., 3.], dtype=float32), tensor([1., 2., 3.], device='cuda:0'))

### Exercise

### Question 1
Create a random tensor with shape (7, 7)

In [100]:
import torch

rand_tensor_1 = torch.rand(7,7)
rand_tensor_1, rand_tensor_1.size, rand_tensor_1.shape

(tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
         [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
         [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
         [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
         [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
         [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
         [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]]),
 <function Tensor.size>,
 torch.Size([7, 7]))

### Question 2
Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [101]:
rand_tensor_2 = torch.rand(1, 7)
rand_tensor_3 = torch.mm(rand_tensor_1, rand_tensor_2.T)
rand_tensor_3, rand_tensor_3.size, rand_tensor_3.shape

(tensor([[1.2748],
         [1.1652],
         [1.0182],
         [1.7959],
         [1.6076],
         [1.8623],
         [0.7118]]),
 <function Tensor.size>,
 torch.Size([7, 1]))

### Question 3
Set the random seed to 0 and do exercises 2 & 3 over again.

In [104]:
SEED = 0

# question 1
torch.manual_seed(SEED)
rand_tensor_1 = torch.rand(7,7)

# question 2
torch.manual_seed(SEED)
rand_tensor_2 = torch.rand(1, 7)
rand_tensor_3 = torch.mm(rand_tensor_1, rand_tensor_2.T)
rand_tensor_3, rand_tensor_3.size, rand_tensor_3.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 <function Tensor.size>,
 torch.Size([7, 1]))

### Question 4
Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [105]:
torch.cuda.manual_seed(1234)

### Question 5
Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [106]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

In [109]:
torch.manual_seed(1234)
a = torch.rand(2, 3)

torch.manual_seed(1234)
b = torch.rand(2, 3)

# send both tensors to available gpu
device = 'cuda' if torch.cuda.is_available() else 'cpu'

torch.manual_seed(1234)
a_on_gpu = a.to(device)

torch.manual_seed(1234)
b_on_gpu = b.to(device)

### Question 6
Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [119]:
# Checking the shapes of both matrices
print(a_on_gpu.shape, b_on_gpu.shape) # either transpose a or tanspose b

# perform matrix multiplication of the tensors on GPU
mat_mul_gpu = torch.mm(a_on_gpu, b_on_gpu.T)
mat_mul_gpu, mat_mul_gpu.size, mat_mul_gpu.shape

torch.Size([2, 3]) torch.Size([2, 3])


(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]], device='cuda:0'),
 <function Tensor.size>,
 torch.Size([2, 2]))

### Question 7
Find the maximum and minimum values of the output of 7.

In [120]:
print(f'Maximum: {torch.max(mat_mul_gpu)}, \nMinimum: {torch.min(mat_mul_gpu)}')

Maximum: 0.628727912902832, 
Minimum: 0.21611443161964417


### Question 8
Find the maximum and minimum index values of the output of 7.

In [121]:
print(f'Max index: {torch.argmax(mat_mul_gpu)}, \nMin index: {torch.argmin(mat_mul_gpu)}')

Max index: 3, 
Min index: 1


### Question 9
Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [128]:
torch.manual_seed(7)
c = torch.rand(1, 1, 1, 10)

torch.manual_seed(7)
c_squeezed = torch.squeeze(c)

print(f'Original tensor: {c}, shape:{c.shape}\n')
print(f'Squeezed tensor: {c_squeezed}, shape: {c_squeezed.shape}')

Original tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), shape:torch.Size([1, 1, 1, 10])

Squeezed tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), shape: torch.Size([10])
